FROM node:18-alpine3.14

ENV HOST=0.0.0.0

WORKDIR /project/

COPY package.json yarn.lock ./
COPY web/package.json  ./web/package.json
RUN yarn

COPY web ./web


ENTRYPOINT ["yarn", "workspace", "web", "dev"]
